services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./api/.env.local
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/notesdb
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: bun run dev

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
      target: builder
    ports:
      - "3000:3000"
    env_file:
      - ./front/.env.local
    environment:
      - NODE_ENV=development
      - NUXT_PUBLIC_API_URL=http://localhost:3001
      - NUXT_PUBLIC_WS_URL=ws://localhost:3001/ws
    working_dir: /usr/src/app/front
    volumes:
      - ./front:/usr/src/app/front
      - /usr/src/app/node_modules
      - /usr/src/app/front/node_modules
      - /usr/src/app/front/.nuxt
      - /usr/src/app/front/.output
    command: pnpm run dev --host 0.0.0.0

volumes:
  postgres_data:
