apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: my-app-project
type: Opaque
stringData:
  POSTGRES_PASSWORD: CHANGE_ME_STRONG_DB_PASSWORD
  JWT_SECRET: CHANGE_ME_LONG_RANDOM_JWT_SECRET
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-app-project
data:
  DB_HOST: postgres-service
  POSTGRES_USER: postgres
  DB_NAME: my_database
  API_URL: https://api.notesaides.app
  API_INTERNAL_URL: http://backend-service
  PORT: "3000"